ARG MARATHON_VERSION=v1.4.5
FROM mesosphere/marathon:$MARATHON_VERSION

ARG APP_VERSION=1.0-SNAPSHOT

ADD build/distributions/marathon-vault-plugin-${APP_VERSION}.tar /plugins/
COPY plugin-conf-test.json /plugin-conf-test.json
