FROM mesosphere/marathon:latest

ADD build/distributions/marathon-vault-plugin-1.0-SNAPSHOT.tar /plugins/
COPY src/main/resources/cz.petrk.marathon.plugin.vault/plugin-conf.json /plugin-conf.json
